### ISSUE TITLE
GeoGebra-Linux-Portable-5-0-367-0.tar.bz2: Server returned status 404: Not Found

### ISSUE THREAD

**Issue by Elinvention** [flathub/org.geogebra.GeoGebra#1]
error: While downloading https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-367-0.tar.bz2: Server returned status 404: Not Found

**Comment by manuq** [comment]
Thanks for the report. Yes they have removed the file :-1: 

There is now a GeoGebra-Linux-Portable-5-0-377-0.tar.bz2 available in their download page. I will change the manifest.
