### ISSUE TITLE
Maybe use Classic 6

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.geogebra.GeoGebra#12]
@manuq is there a reason we use the Classic 5 version of GeoGebra here (Java based) rather than the Classic 6 version (Electron based). It seems to be a 100mb smaller download, for instance. No worries if so - just interested.

**Comment by manuq** [comment]
@nedrichards no reason to not use v6. I think I found v5 first. So I will give this a try, thanks for noticing!

**Comment by LeandroStanger** [comment]
How is progress going to version 6?
