### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.geogebra.GeoGebra#13]
![captura de tela de 2018-01-24 21-55-21](https://user-images.githubusercontent.com/26097419/35363523-7a625e2e-0151-11e8-8912-3c1fdcffe90b.png)

**Comment by LeandroStanger** [comment]
https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-422-0.tar.bz2

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by nedrichards** [comment]
@LeandroStanger I've had a look. Next time, feel free to send a PR. All you really need is the new URL, the size from `ls -l` in the directory and the `sha256sum` of the file. Then just change the version numbers in the right place in the JSON. There are plenty of people on flathub to review and help you get better.
