### ISSUE TITLE
404 Error (fixed by update)

### ISSUE THREAD

**Issue by mwt** [flathub/org.geogebra.GeoGebra#138]
The download for the referenced version has been removed.
```
error: Failed to install org.geogebra.GeoGebra: While downloading https://download.geogebra.org/installers/6.0/GeoGebra-Linux64-Portable-6-0-697-0.zip: Server returned status 404: Not Found
```

Fixed by merging #137 (or one of the other automatic update pulls)

**Comment by foopsss** [comment]
Tagging some of the contributors so they can be aware of this: @LeandroStanger @dgcampea @manuq.

**Comment by Atheror** [comment]
It needs update, new version is located at https://download.geogebra.org/installers/6.0/GeoGebra-Linux64-Portable-6-0-706-0.zip

**Comment by foopsss** [comment]
Tagging another contributor: @cho2.

**Comment by dgcampea** [comment]
The repo uses _flatpak-external-data-checker_ but the updates still need to be manually merged by someone with commit access.
Usually this is handled by @LeandroStanger but if he's unreachable you might have better luck contacting the flathub maintainers.

cc @TingPing

**Comment by cho2** [comment]
> The repo uses flatpak-external-data-checker but the updates still need to be manually merged by someone with commit access.
Usually this is handled by @LeandroStanger but if he's unreachable you might have better luck contacting the flathub maintainers.

See https://github.com/flathub/org.geogebra.GeoGebra/pulls, 5 pull request here, and I don't have access to merge it.

cc also @flathub/reviewers

**Comment by barthalion** [comment]
I merged the latest PR and added @cho2 to collaborators.

@cho2, I would consider enabling automatic f-e-d-c merges given it's an extra-data app.
