### ISSUE TITLE
Beta?

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.geogebra.GeoGebra#153]
Why is this Flatpak called a beta? https://github.com/flathub/org.geogebra.GeoGebra/blob/master/org.geogebra.GeoGebra.desktop#L3

**Comment by cho2** [comment]
Looks like it's from 2019 commit https://github.com/flathub/org.geogebra.GeoGebra/commit/e76660c578af4c3e11f4583b97ff5b08d0e92e4c
