### ISSUE TITLE
404 Error while installing

### ISSUE THREAD

**Issue by duesenfranz** [flathub/org.geogebra.GeoGebra#16]
While trying to install, gnome software says `Installation of GeoGebra not possible. While downloading https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-422-0.tar.bz2: Server returned status 404: Not Found`

The flatpak tries to download the portable version from an old url, which seems to be [here](https://github.com/flathub/org.geogebra.GeoGebra/blob/a06dbbcbe1155673e845434a4c9415c75fc1200c/org.geogebra.GeoGebra.json#L73).

The download link [on the geogebra site](https://wiki.geogebra.org/en/Reference%3AGeoGebra_Installation?note=de#Others) points to `https://download.geogebra.org/package/linux-port`, for which the server returns a `302 Moved Temporarily` and the real location to the portable archive.

The wrong (old) url is
`https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-422-0.tar.bz2`,
the new one `https://download.geogebra.org/installers/5.0/GeoGebra-Linux-Portable-5-0-427-0.tar.bz2`; but if they regularily delete old archives, just updating the link is probably more of a short-term solution.

Ideally you would probably rehost the sources & binaries, but probably requires a lawyer to read through the [license](https://geogebra.org/license). (On the other hand, many linux repositories rehost geogebra.) Alternatively you could just write  mail to `office@geogebra.org` and request official permission?

**Comment by nedrichards** [comment]
Fixed, for now - by https://github.com/flathub/org.geogebra.GeoGebra/commit/c4e3c36dab8de4c11786b5e75095195587c460ad better monitoring will be added for all apps of this type soon.

**Comment by duesenfranz** [comment]
Thanks! :)

Rehosting the binary is not on the table?

**Comment by TingPing** [comment]
@duesenfranz It is proprietary, I couldn't find an exact license on their website but it probably doesn't allow redistribution.

**Comment by nedrichards** [comment]
Yeah, we can't rehost that. We probably could build it from scratch - since the source is fully open - but I'm not sure what if anything requires proprietry integration. This is a case similar to Visual Studio Code.
